name: covid
channels:
  - conda-forge
dependencies:
  - ipykernel
  - pip
  - pandas
  - pandas-profiling
  - matplotlib
  - ipympl
  - tabula-py
  - scipy
  - lxml
  - beautifulsoup4
  - html5lib
  - PyPDF2
  - seaborn
  - tqdm
  - seir
  - pip:
    - cbsodata
    - epyestim
    - epintervene
